### PR TITLE
Add tests for ZKP Verifiable Credentials

### PR DESCRIPTION
**Pull request by brentzundel**
Adds tests to the test suite for normative language around verifiable credentials that use ZKPs.

### CODE REVIEW

**Comment by dmitrizagidulin** [comment]
Oh wow, nice!

**Comment by dmitrizagidulin** [comment]
+1, this looks great.

One minor request: can you change the examples `"type": "example"` occurrences to some appropriate type (not sure if it's `CLProofDefinition2019` or something else, off the top of my head), just to match what I'm doing in https://github.com/w3c/vc-test-suite/pull/32 ?

**Comment by brentzundel** [comment]
> One minor request: can you change the examples `"type": "example"` occurrences to some appropriate type (not sure if it's `CLProofDefinition2019` or something else, off the top of my head), just to match what I'm doing in #32 ?

Addressed in [8af624c](https://github.com/w3c/vc-test-suite/pull/35/commits/8af624c961f30eb618ee76d0aff791b3b0d60dcd)

**Comment by dmitrizagidulin** [comment]
Thanks @brentzundel! 👍 from me.

**Pull request merged**
