### PR TITLE
added support for JWT test cases support

### PR DESCRIPTION
**Pull request by awoie**
added support for JWT test cases support
- according to sequence diagram in assets folder
- 50-jwt.js now tests VC spec JWT MUST statements
- config.json.jwt.example shows command line options for JWT generators

### CODE REVIEW

**Comment by awoie** [comment]
@dmitrizagidulin could you please review to allow us and others to upload test reports on time :)

**Comment by TallTed** [comment]
We've still got problems with `nbf` ("Not Before", the actual semantic intent of `issuanceDate`) vs `iat` ("Issued At", the incorrect but closest simple-language match).

(Double problems, as I think these tests now match the spec as it stands, but the spec needs to be corrected, and the tests need to be corrected to match.)

**Comment by stonematt** [comment]
Pull this PR in after the switch to the `nbf` claim type

**Comment by dmitrizagidulin** [comment]
@awoie Thanks! (Do you mind rebasing on latest, to remove the conflict?)

**Comment by awoie** [comment]
pr should be fine now (rebased) and contains the nbf change @dmitrizagidulin @TallTed

**Comment by awoie** [comment]
@dmitrizagidulin is there any chance of getting this PR in this week? (i don't have permissions to assign reviewers or do other things in this repo)

**Pull request merged**
