### PR TITLE
Create Toulouse-Kent-report.json

### PR DESCRIPTION
**Pull request by David-Chadwick**

### CODE REVIEW

**Comment by David-Chadwick** [comment]
[guillaumeDAUMAS-VCtestreport.txt](https://github.com/w3c/vc-test-suite/files/3346667/guillaumeDAUMAS-VCtestreport.txt)

**Comment by dmitrizagidulin** [comment]
@David-Chadwick - thanks for the two implementations reports! I've merged them into PR #64 and included them in the updated report HTML, so I'm closing this PR.

**Comment by David-Chadwick** [comment]
[Toulouse-Kent-newReport.json.txt](https://github.com/w3c/vc-test-suite/files/3485564/Toulouse-Kent-newReport.json.txt)

**Comment by dmitrizagidulin** [comment]
@David-Chadwick - Do you have a link or a github repo for the Toulose-Kent implementation? (To add to the report table as metadata)

**Comment by TallTed** [comment]
(Maybe it doesn't matter, but it seems like this new/updated report should be submitted through a new PR, not by reopening this previous PR which was already merged via #64.)

**Comment by dmitrizagidulin** [comment]
@TallTed - no worries, I'm making a new PR for this.

**Comment by dmitrizagidulin** [comment]
(Moved Toulouse-Kent report from comment .txt to PR #89). Closing this one.

**Pull request closed without merging**
