### PR TITLE
Stub out MUSTs

### PR DESCRIPTION
**Pull request by BigBlueHat**
I'm working through the tests to add all the remaining MUSTs.

I wanted to send this in for an early review to make sure I'm coming at this the right way. This PR also includes a few tweaks (small ones!) to the overall test suite, and I can put those in a separate PR if preferred.

Cheers!
🎩

### CODE REVIEW

**Review by msporny — APPROVED** [review]

**Comment by msporny** [comment]
modulo package-lock.json - let's not commit that and prevent that from being committed.

**Comment by BigBlueHat** [comment]
> modulo package-lock.json - let's not commit that and prevent that from being committed.

Addressed in this updated PR. I'll continue through the other MUSTs tomorrow. Cheers!

**Comment by msporny** [comment]
Heads up that I refactored how the test suite is organized, just more mocha test files, shouldn't be difficult to rebase on top of it.

**Comment by msporny** [comment]
I have made a complete pass through the specification (commits https://github.com/w3c/vc-data-model/commit/175f07e1a10a6f8e6f9ee5242429d3360ccf2f06 and https://github.com/w3c/vc-data-model/commit/30591535e6efe7535cecadc18baa5c12cd8adc94) and ensured that all MUSTs, RECOMMENDED, SHOULDs, MAYs (and their respective NOTs), specifically talk about document conformance and do not talk about issuer, holder, or verifier conformance.

This means that all conformance language in the spec should be clean at this point (making it safe to attempt to write tests for all conformance statements in the spec). Some of the statements aren't testable w/o specific RDF vocabs that test the functionality, so I expect that we won't be writing those tests in the test suite. In any case, let's get all of the MUSTs into the test suite first and then go from there.

**Comment by BigBlueHat** [comment]
This is just a rebase at this point, but working through the rest of them today! Cheers!

**Comment by BigBlueHat** [comment]
More coming beyond these, but I think these last 3 are ready for review.

**Comment by BigBlueHat** [comment]
@msporny lots of little questions throughout these last PRs. Some spec related; some test suite related.

**Comment by BigBlueHat** [comment]
@msporny k. I think I've got the bulk of the test-able (i.e. data-model) requirements with the exception of JWT related tests (though I did stub some of that out also--but they definitely need work).

There are `TODO` notes throughout for stuff that wasn't quite spec related. Also general musings throughout. :wink:

*Please* let me know if I can help with any more of this or if these need changes.

Cheers!
🎩

**Comment by msporny** [comment]
LGTM, merging.

**Pull request merged**
